"""add_email_status

Revision ID: 2d1d8aa4e94c
Revises: 400ace231732
Create Date: 2026-05-06 14:01:16.106350

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d1d8aa4e94c'
down_revision: Union[str, None] = '400ace231732'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applications', sa.Column('email_status', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('applications', 'email_status')
    # ### end Alembic commands ###
