"""add_device_auth_fields

Revision ID: 400ace231732
Revises: 47cf1feecc50
Create Date: 2026-04-25 19:04:09.470787

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '400ace231732'
down_revision: Union[str, None] = '47cf1feecc50'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sessions')
    op.add_column('devices', sa.Column('pairing_ip', postgresql.INET(), nullable=True))
    op.add_column('devices', sa.Column('last_ip', postgresql.INET(), nullable=True))
    op.add_column('devices', sa.Column('last_user_agent', sa.Text(), nullable=True))
    # Postgres cannot implicitly cast bytea->text; use a raw USING clause.
    # The existing unique constraint on public_key is preserved automatically.
    op.execute(
        "ALTER TABLE devices ALTER COLUMN public_key TYPE TEXT "
        "USING encode(public_key, 'escape')"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        "ALTER TABLE devices ALTER COLUMN public_key TYPE BYTEA "
        "USING decode(public_key, 'escape')"
    )
    op.drop_column('devices', 'last_user_agent')
    op.drop_column('devices', 'last_ip')
    op.drop_column('devices', 'pairing_ip')
    op.create_table('sessions',
    sa.Column('token_hash', postgresql.BYTEA(), autoincrement=False, nullable=False),
    sa.Column('device_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('issued_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('rotates_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('revoked_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('token_hash', name='sessions_pkey')
    )
    # ### end Alembic commands ###
