"""add_starred_dismissed_to_jobs

Revision ID: 7cb2e2ceea6a
Revises: 2d1d8aa4e94c
Create Date: 2026-05-06 21:56:53.775170

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7cb2e2ceea6a'
down_revision: Union[str, None] = '2d1d8aa4e94c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('starred', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('jobs', sa.Column('dismissed', sa.Boolean(), nullable=False, server_default='false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'dismissed')
    op.drop_column('jobs', 'starred')
    # ### end Alembic commands ###
